# action.yml
name: "Cowsay Message"
description: "Greet someone and print Cowsay message"
author: "Alpha Olomi"
inputs:
  message:
    description: "Custom Message"
    required: false
    default: "Hello World"
outputs:
  msg:
    description: "The cowsay meesage"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{e inputs.message }}

branding:
  icon: "message-circle"
  color: "green"
