on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to cowsay
    steps:
    - name: Hello world action step
      id: hello
      uses: alphaolomi/hello-world-docker-action@v1.0.0-a
      with:
        message: 'Hellowwww'
    - name: Get the output time
      run: echo "${{ steps.hello.outputs.msg }}"
